title: YNBD
email:
description: Yana Bechard's portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yanabechard.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  ynbd
enforce_ssl: 'yanabechard.com'

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
